apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment-{{ .Release.Namespace }}
  labels: 
    app: movie-{{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: movie-deployment-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: movie-deployment-{{ .Release.Namespace }}
    spec:
      containers:
      - name: movie
        image: "{{ .Values.image.movie.repository }}:{{ .Values.image.movie.tag }}" 
        command: ["sh", "-c"] # ["uvicorn", "app.main:app"]
        args: ["uvicorn app.main:app --host 0.0.0.0 --port 8000"] # ["--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        envFrom:
          - configMapRef:
              name: movie-configmap-{{ .Release.Namespace }}
          - secretRef:
              name: movie-secret-{{ .Release.Namespace }}
        volumeMounts:
          - name: movie-volume-{{ .Release.Namespace }}
            mountPath: /app/data
      volumes:
        - name: movie-volume-{{ .Release.Namespace }}
          persistentVolumeClaim:
            claimName: movie-pvc-{{ .Release.Namespace }}
