apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cast-configmap-{{ .Release.Namespace }}
  labels:
    app: cast-{{ .Release.Namespace }}
data:
  POSTGRES_USER: cast_db_username
  POSTGRES_DB: cast_db_dev
